FROM docker.io/nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY web/index.html /usr/share/nginx/html/index.html
COPY web/avatar_mcorpas.png /usr/share/nginx/html/avatar_mcorpas.png
COPY certs/server.crt /etc/nginx/certs/server.crt
COPY certs/server.key /etc/nginx/certs/server.key
COPY htpasswd /etc/nginx/htpasswd

EXPOSE 443
